---

- name: Set Base PAM Limits (Soft)
  pam_limits:
    domain="*"
    limit_type="soft"
    limit_item="{{ item.key }}"
    value="{{ item.value.soft }}"
    use_max="yes"
  with_dict: "{{ server_pam }}"

- name: Set Base PAM Limits (Hard)
  pam_limits:
    domain="*"
    limit_type="hard"
    limit_item="{{ item.key }}"
    value="{{ item.value.hard }}"
    use_max="yes"
  with_dict: "{{ server_pam }}"

- name: Set Base Sysctl
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
  with_items: "{{ server_sysctl }}"

- name: Set Extra Sysctl
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
  with_items: "{{ server_extra_sysctl }}"

- name: Reload Sysctl
  sysctl:
    reload="yes"
