---

- name: Bump User File Limits (Hard)
  pam_limits:
    domain="*"
    limit_type="hard"
    limit_item="nofile"
    value="{{ server_pam.nofile.hard }}"
    use_max="yes"

- name: Bump User File Limits (Soft)
  pam_limits:
    domain="*"
    limit_type="soft"
    limit_item="nofile"
    value="{{ server_pam.nofile.soft }}"
    use_max="yes"

- name: Bump User Proc Limits (Hard)
  pam_limits:
    domain="*"
    limit_type="hard"
    limit_item="nproc"
    value="{{ server_pam.nproc.hard }}"
    use_max="yes"

- name: Bump User Proc Limits (Soft)
  pam_limits:
    domain="*"
    limit_type="soft"
    limit_item="nproc"
    value="{{ server_pam.nproc.soft }}"
    use_max="yes"

- name: Update Sysctl (net.core.somaxconn)
  sysctl:
    name="net.core.somaxconn"
    value="{{ server_sysctl.net_core_somaxconn }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"

- name: Update Sysctl (net.ipv4.ip_local_port_range)
  sysctl:
    name="net.ipv4.ip_local_port_range"
    value="{{ server_sysctl.net_ipv4_ip_local_port_range }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"

- name: Update Sysctl (net.ipv4.tcp_tw_recycle)
  sysctl:
    name="net.ipv4.tcp_tw_recycle"
    value="1"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"

- name: Update Sysctl (fs.file-max)
  sysctl:
    name="fs.file-max"
    value="{{ server_sysctl.fs_file_max }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
    reload="yes"
