---

- name: Set the Hostname
  hostname:
    name="{{ inventory_hostname }}"
  ignore_errors: "yes"

- name: Set the Global PATH
  lineinfile:
    dest="/etc/environment"
    state="present"
    line="PATH={{ server_extra_path }}:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  when: server_extra_path != ''

- name: Install Extras
  yum:
    name="{{ item }}"
    state="present"
    disablerepo="*"
    enablerepo="epel, base, updates, nexcess, extras"
  with_items: "{{ server_packages + server_extra_packages }}"

- name: Turn Off Unused Services
  service:
    name="{{ item }}"
    enabled="no"
    state="stopped"
  with_items: "{{ server_services_unused }}"
  ignore_errors: yes

- include: limits.yml
  when: server_adjust_limits

- name: Setup /etc/hosts
  template:
    src="hosts.j2"
    dest="/etc/hosts"
    owner="root"
    group="root"
    mode="0644"

- name: Make Sure Known Hosts File Exists
  file:
    path="{{ server_ssh_known_hosts_file }}"
    state="touch"

- name: Suck in Known Hosts
  shell: "ssh-keygen -f {{ server_ssh_known_hosts_file }} -F {{ item }}"
  with_items: "{{ server_ssh_known_hosts }}"
  register: server_ssh_known_host_results
  ignore_errors: yes

- name: Scan the Public Key
  shell: "{{ server_ssh_known_hosts_command }} {{ item.item }} >> {{ server_ssh_known_hosts_file }}"
  with_items: "{{ server_ssh_known_host_results.results }}"
  when: item.stdout == ""

- name: Setup our Aliases
  lineinfile:
    dest="/etc/profile.d/aliases.sh"
    create="yes"
    owner="root"
    group="root"
    mode="0644"
    line='alias {{ item.key }}="{{ item.value }}"'
    regexp="^alias {{ item.key }}="
  with_dict: "{{ server_bash_aliases }}"

- name: Update Base System
  command: /bin/true
  notify: server update
  when: server_update
