---

- name: Set the Global PATH
  lineinfile:
    dest="/etc/environment"
    state="present"
    line="PATH={{ server_extra_path }}:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  when: server_extra_path != ''

- name: Install Extras
  yum:
    name="{{ item }}"
    state="present"
  with_items: "{{ server_packages }}"

- name: Turn Off Unused Services
  service:
    name="{{ item }}"
    enabled="no"
    state="stopped"
  with_items: "{{ server_services_unused }}"
  ignore_errors: yes

- include: limits.yml
  when: server_adjust_limits

- name: Setup /etc/hosts
  template:
    src="hosts.j2"
    dest="/etc/hosts"
    owner="root"
    group="root"
    mode="0644"

- name: Update Base System
  command: /bin/true
  notify: server update
  when: server_update
