- name: Set Base Sysctl
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
    reload="yes"
  with_items: "{{ server_sysctl }}"
  tags:
    - kernel-sysctl
    - kernel-sysctl-base

- name: Set Sysctl For 10G Networking
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
    reload="yes"
  with_items: "{{ server_sysctl_10g }}"
  when: server_set_sysctl_10g
  tags:
    - kernel-sysctl
    - kernel-sysctl-10g

- name: Set Extra Sysctl
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state="present"
    sysctl_set="yes"
    ignoreerrors="yes"
    reload="yes"
  with_items: "{{ server_extra_sysctl }}"
  tags:
    - kernel-sysctl
    - kernel-sysctl-extra
